### ISSUE TITLE
Adguard Home 插件工作异常

### ISSUE THREAD

**Issue by mrniceguy999** [thomaswcy/R2S#17]
2021.08.09 RubikWrt (Stable WAN/LAN)
插件一直处于无法关闭也无法开启重定向的状态，并且在192.168.2.1:3000设置的端口及DNS没有反映到插件的配置文件上。

**Comment by thomaswcy** [comment]
AdGuardHome么？

**Comment by thomaswcy** [comment]
> 2021.08.09 RubikWrt (Stable WAN/LAN)
> 插件一直处于无法关闭也无法开启重定向的状态，并且在192.168.2.1:3000设置的端口及DNS没有反映到插件的配置文件上。

你要在翻墙插件DNS设置那边选择本地端口那个

**Comment by thomaswcy** [comment]
![image](https://user-images.githubusercontent.com/62056970/129300607-044cb39d-ae23-4f88-9365-6bf2d36c3eec.png)
像这样就ok了
